version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - src/.env

  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iyzads
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
