services:
  iyzads-app:
    container_name: 'iyzads-app'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - src/.env

  postgres:
    container_name: 'iyzads-postgres'
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iyzads
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
